// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type RefreshToken struct {
	Token     string
	CreatedAt string
	UpdatedAt string
	UserID    string
	ExpiresAt string
	RevokedAt sql.NullString
}

type User struct {
	ID           string
	Username     string
	Email        string
	PasswordHash string
	AvatarUrl    sql.NullString
	VoiceUrl     sql.NullString
	IsAdmin      int64
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
