// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type User struct {
	ID           string
	Username     string
	Email        string
	PasswordHash string
	AvatarUrl    sql.NullString
	VoiceUrl     sql.NullString
	IsAdmin      int64
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
