// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: musics.sql

package database

import (
	"context"
	"database/sql"
)

const createMusicMeta = `-- name: CreateMusicMeta :one
INSERT INTO musics(id, user_id, title, description )
VALUES(
    ?,
    ?,
    ?,
    ?
)RETURNING id, title, description, user_id, s3_url, created_at, updated_at
`

type CreateMusicMetaParams struct {
	ID          string
	UserID      string
	Title       string
	Description sql.NullString
}

func (q *Queries) CreateMusicMeta(ctx context.Context, arg CreateMusicMetaParams) (Music, error) {
	row := q.db.QueryRowContext(ctx, createMusicMeta,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
	)
	var i Music
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.UserID,
		&i.S3Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMusic = `-- name: DeleteMusic :one
DELETE FROM musics WHERE id = ? AND user_id = ? RETURNING id, title, description, user_id, s3_url, created_at, updated_at
`

type DeleteMusicParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteMusic(ctx context.Context, arg DeleteMusicParams) (Music, error) {
	row := q.db.QueryRowContext(ctx, deleteMusic, arg.ID, arg.UserID)
	var i Music
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.UserID,
		&i.S3Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMusicById = `-- name: GetMusicById :one
SELECT id, title, description, user_id, s3_url, created_at, updated_at FROM musics WHERE id = ?
`

func (q *Queries) GetMusicById(ctx context.Context, id string) (Music, error) {
	row := q.db.QueryRowContext(ctx, getMusicById, id)
	var i Music
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.UserID,
		&i.S3Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMusicByUser = `-- name: GetMusicByUser :many
SELECT id, title, description, user_id, s3_url, created_at, updated_at FROM musics WHERE user_id = ?
`

func (q *Queries) GetMusicByUser(ctx context.Context, userID string) ([]Music, error) {
	rows, err := q.db.QueryContext(ctx, getMusicByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Music
	for rows.Next() {
		var i Music
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.UserID,
			&i.S3Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMusic = `-- name: UpdateMusic :exec
UPDATE musics
SET
    title = ?,
    description = ?,
    user_id = ?,
    s3_url = ?
WHERE id = ?
`

type UpdateMusicParams struct {
	Title       string
	Description sql.NullString
	UserID      string
	S3Url       sql.NullString
	ID          string
}

func (q *Queries) UpdateMusic(ctx context.Context, arg UpdateMusicParams) error {
	_, err := q.db.ExecContext(ctx, updateMusic,
		arg.Title,
		arg.Description,
		arg.UserID,
		arg.S3Url,
		arg.ID,
	)
	return err
}
